### ISSUE TITLE
Sprint Planning

### ISSUE THREAD

**Issue by vanemanza** [vanemanza/Proyecto_Grupal_ISPC#10]
Definición - Participantes

**Comment by dayanalucchesi** [comment]
**Definición**
La planificación de sprints es un evento en scrum que inicia el sprint. El objetivo de la planificación de sprints es definir lo que se puede entregar en el sprint y cómo se conseguirá ese trabajo. La planificación de sprints se hace en colaboración con todo el equipo de scrum.
Consta de dos segmentos:
_Segmento uno:_ 

-  El Product Owner presenta el Backlog de Producto con mas alta prioridad.
- El equipo selecciona los items del Backlog de Producto con los que se pueden comprometer.

_Segmento dos:_

- Decidir la estrategia para alcanzar el objetivo del sprint (diseño).
- Las tareas son creadas.
- Se estiman las tareas y el backlog de sprint.
- De manera colaborativa, no solamente el Scrum Master.


**Participantes**
En esta etapa deben estar presentes:
- Scrum Master
- Product Owner
- Developer Team

Nota: El concepto principal de definicion de Planificacion de Sprint se extrajo de [Definicion de Planificacion de Sprint](https://www.ariadgroup.com/es/blog/todo-sobre-scrum-agile-metodologia/los-componentes-ceremonias-scrum-todos-detalles)
