### ISSUE TITLE
Manifiesto Agil

### ISSUE THREAD

**Issue by vanemanza** [vanemanza/Proyecto_Grupal_ISPC#5]
Definición, nombrar Valores y Principios. Procesos Agiles.

**Comment by flavioapalacios** [comment]
Terminado

**Comment by flavioapalacios** [comment]
Son:  métodos alternativos de trabajo definidos y resumidos en los siguientes postulados:

Estamos descubriendo formas mejores de desarrollar software tanto por nuestra propia experiencia como ayudando a terceros. A través de este trabajo hemos aprendido a valorar:

- Individuos e interacciones sobre procesos y herramientas
- Software funcionando sobre documentación extensiva
- Colaboración con el cliente sobre negociación contractual
- Respuesta ante el cambio sobre seguir un plan

Esto es, aunque valoramos los elementos de la derecha, valoramos más los de la izquierda.
