### ISSUE TITLE
Sprint - Ceremonias

### ISSUE THREAD

**Issue by vanemanza** [vanemanza/Proyecto_Grupal_ISPC#9]
Nombrarlas y describir brevemente.

**Comment by dayanalucchesi** [comment]
**Ceremonias que se realizan a lo largo del proyecto:**

● **_Sprint Planning Meeting:_**

 (reunión de planificación del sprint). Se produce al iniciar cada
Sprint y tiene por objetivo decidir que se va a realizar en el Sprint.

● **_Daily Scrum Meeting:_** (reunión periódica). Se produce diariamente, y tiene un máximo de
20 min. de duración. Tiene por objeto tratar qué es lo que se hizo, qué se va a hacer y
qué problemas se han encontrado, esto a fines de encontrar soluciones en la diaria.

● **_Sprint Review Meeting:_**
 (reunión de revisión del Sprint). Se produce al finalizar el Sprint y
tiene por objeto mostrar qué es lo que se ha completado y qué no. Debe estar presente el
Product Owner.

● **_Sprint Retrospective Meeting:_**(reunión de retrospectiva del Sprint):
Se produce también al
finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado
en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que
debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.
